# A single Render blueprint (definition of services)
services:
  - type: web
    name: your-app-name # Choose a unique name for your web service
    env: python # Primary language is Python
    # Use the custom build script
    buildCommand: bash render_build.sh
    # Start command for Gunicorn, runs from ./src/ as per Procfile
    startCommand: gunicorn wsgi --chdir ./src/
    # Environment variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name # Link to your database service below
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true # Render can generate a secure random value for you
      - key: FLASK_DEBUG
        value: "0" # Set to "0" for production
    # Runtime versions
    autoDeploy: true # Set to false if you want manual deploys
    # Define ports if needed, but Render usually handles this if your app listens on $PORT
    # port: 3001 # Your app.py uses 3001 as default, but Render sets $PORT dynamically
    disk:
      name: my-flask-app-disk
      mountPath: /var/lib/data # Example if you need persistent storage

# Define a PostgreSQL database service
databases:
  - name: your-database-name # Choose a unique name for your database
    ipAllowList: [] # Allow all incoming connections for simplicity, or specify IPs