"""empty message

Revision ID: 549c6a8ca258
Revises: 00f9fa714346
Create Date: 2025-06-12 16:20:41.143271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549c6a8ca258'
down_revision = '00f9fa714346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
